version: 2.1
executors:
  npm:
    environment:
    working_directory: ~/ngv-form-decorators
    docker:
      - image: circleci/node:10-browsers-legacy
jobs:
  update_dependencies:
    executor: npm
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  lint:
    executor: npm
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: lint
          command: npm run lint ngv-form-decorators
  build:
    executor: npm
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: build
          command: npm run build:ngv-form-decorators
      - store_artifacts:
          path: dist/ngv-form-decorators
          destination: ngv-form-decorators
      - save_cache:
          key: dist-ngv-form-decorators{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - ./dist/ngv-form-decorators
  deploy-package:
    executor: npm
    steps:
      - restore_cache:
          key: dist-ngv-form-decorators{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: npm publish
          command: |
            cd dist/ngv-form-decorators
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN">.npmrc
            npm publish --access public
  test:
    executor: npm
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: test
          command: npm run test ngv-form-decorators -- --watch false --code-coverage   --progress false
      - store_test_results:
          path: coverage/clover
      - run:
          name: coverage
          command:  bash <(curl -s https://codecov.io/bash)
  build-docs:
    executor: npm
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}
      - run:
          name: build-docs
          command:  npm run build -- --prod --base-href "https://ng-veteran.github.io/ngv-form-decorators/" --progress false
      - save_cache:
          key: dist-ngv-form-decorators-demo{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - ./dist/ngv-form-decorators-demo
            - ./node_modules
      - store_artifacts:
          path: dist/ngv-form-decorators-demo
          destination: ngv-form-decorators-demo
  deploy-docs:
    executor: npm
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-ngv-form-decorators-demo{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run:
          name: deploy
          command: npm run ghpages -- --repo https://github.com/ng-veteran/ngv-form-decorators  --dir dist/ngv-form-decorators-demo --no-silent --name cller --email change_job@outlook.com
workflows:
  version: 2.1
  publish:
    jobs:
      - update_dependencies:
          filters:
            branches:
              ignore:
                - gh-pages
              only: master
            tags:
              only: /^v.*/
      - lint:
          requires:
            - update_dependencies
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - update_dependencies
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - update_dependencies
          filters:
            tags:
              only: /^v.*/
      - build-docs:
          requires:
            - update_dependencies
          filters:
            tags:
              only: /^v.*/
      - deploy-package:
          requires:
            - lint
            - test
            - build
            - build-docs
          filters:
            branches:
              ignore:
                - master
            tags:
              only: /^v.*/
      - deploy-docs:
          requires:
            - lint
            - test
            - build
            - build-docs
          filters:
            branches:
              ignore:
                - master
            tags:
              only: /^v.*/
